model/model.go, primitive/compute/description/preprocessing.go, primitive/compute/description/preprocessing_test.go, primitive/compute/description/primitive_steps.go
Add the denorm step to the dataset pipeline. If it is a timeseries dataset, use the formatter.
=> Model timeseries formatter

primitive/compute/ta3ta2.go
Adds defs and functions to provide default subtasks when given a task, and a default metric when given a task.
=> adds default subtask and metric mappings for tasks

primitive/compute/description/builder.go, primitive/compute/description/builder_test.go, primitive/compute/description/inference_step_data.go, primitive/compute/description/step_data.go
Adds the ability to use a primitive as a hyper parameter argument.
=> Support for primitive reference hyperparameters

primitive/compute/description/builder.go, primitive/compute/description/builder_test.go, primitive/compute/description/inference_step_data.go, primitive/compute/description/preprocessing.go, primitive/compute/description/preprocessing_test.go, primitive/compute/description/primitive_steps.go, primitive/compute/description/step_data.go
Moves pipeline API to be closer to the underlying pipeline description schema and updates all existing pipelines to reflect change.
=> pipeline API update

primitive/compute/description/preprocessing.go, primitive/compute/description/primitive_steps.go
1. Uses statistical guessing for categoricals in Simon
2. Applies column parser before data cleaning to properly deal with numeric data
3. Ensures output arg is applied in dataset wrapper
=> Post -API update pipeline tweaks

model/schema_types.go
resolves uncharted-distil/distil#1036
We were passing unmapped simon types through as suggested types when running ingest.  This lead to the client getting the Simon values of `datetime` and `text` instead of the internal types of `dateTime` and `string`.
=> expands simon typing and adds logging for pass through cases

primitive/compute/description/preprocessing.go, primitive/compute/description/preprocessing_test.go, primitive/compute/description/primitive_steps.go
resolves #37 
Adds column parser and data cleaning to prepend.  This will ensure that all columns are typed properly and bad data is consistently handled.
=> adds column parser and data cleaner to prepend

primitive/compute/ta3ta2.go
Supports resolution of uncharted-distil/distil#1232.  Defines constants for task and sub task types.
=> updates task definitions to use constants

middleware/log_grpc.go, primitive/compute/client.go, primitive/compute/execute_pipeline_request.go
Added describe support as well as the ability to use a search request as template for a subsequent request.
=> Add explain call

middleware/log_grpc.go
Adds params to the grpc discovery log. Currently extracts solution id, fitted solution id and name.
=> Log solution api

primitive/compute/description/preprocessing.go
Ensures that the target column has the `target` semantic type assigned to it when generating semantic type update pipeline steps.
=> adds target semantic type to target col

model/filter.go, primitive/compute/description/fully_specified.go, primitive/compute/description/primitive_steps.go
Created image clustering pipeline and filter type.
=> Image clustering pipeline

model/filter.go, model/model.go, model/schema_types.go
Vector filter type added to support filtering on nested types. Also added a list type to distinguish between a vector construct, and a csv list in the database.
=> Object detection dataset

metadata/metadata.go, metadata/metadata_test.go
Updated variable augmenting when loading from the original schema to be optional.
=> Optional Original Schema Variable Augment

model/model.go
Some datetime fields only have time components. As quick fix, they can now use the datetime format without crashing via a CASE statement & defaulting to epoch time date + time value.
=> Time Only Field

metadata/verification.go, model/model.go, primitive/compute/description/preprocessing.go
Added the multi index role and removed the duplication of the index role.
=> Fix Index Constants

metadata/metadata.go, model/model.go, model/schema_types.go, primitive/compute/description/preprocessing.go
Cleaned up some duplication of constants.
Added remote sensing support when generating a pipeline prepend. Currently checks for a grouping role along with a multi band image variable.
=> Remote sensing grouping

primitive/compute/description/preprocessing.go
User pipeline creation needed access to the grouped variables, but these were being removed from the `UserDataDescription.AllFeatures` list that was passed in as a parameter.  That value now contains the full variable list (what is returned by the `FetchVariables` call), and we filter this list down internally so that we have a version with grouped variables, and one that contains the orignal dataset variables only.  Expansion of the selected variables has also been updated to include group hidden variables, so code to add them manually could be removed.
=> Reflect upstream changes to all features and selected features contents

primitive/compute/description/preprocessing.go
Removed metadata vars for prepend purposes.
=> Metadata Prepend

primitive/compute/description/cluster.go, primitive/compute/description/preprocessing.go
Added a basic pipeline to do general clustering.
=> Cluster all datasets

primitive/compute/description/cluster.go, primitive/compute/description/fully_specified.go
Switches to hdbscan for image clustering pipeline. For now, the parameters are hardcoded.
=> Image clustering hdbscan

metadata/metadata.go, model/model.go, model/schema_types.go
Added missing GeoBounds mapping.
Switched from generic gabs container to defined struct when dealing with classification output.
=> Set types ingest

primitive/compute/description/cluster.go
Added parameter to switch between hdbscan and kmeans clustering.
=> Hdb kmeans config

primitive/compute/description/cluster.go
Cleared up the image clustering and fixed the remote sensing kmeans clustering.
=> KMeans Clustering

model/model.go
Truncation of long dataset names to pg lengths could cut off the deconfliction suffix we apply when a dataset name is a duplicate of another.  We now search for the `_N` suffix, and leave it in place when truncating.  Characters prior to the suffix are removed instead.
=> Preserve any possible deconfliction suffix when normalizing table names

metadata/metadata.go, model/filter.go, model/model.go
Added geometry type and geobounds filtering handling in postgres. 
Also fixed some old errors concerning the handling of original variable data. When loading from the schema doc, it was not looking at the correct field name and so was always defaulting to the variable name.
=> Ingest create geometry

primitive/compute/description/builder.go, primitive/compute/description/cluster.go
Adds new pipelines for k-means and hdbscan clustering of pre-featurized remote sensing data.
=> Pre-featurized clustering support

model/model.go, model/schema_types.go
Removed postgres related code as that belongs in distil.
Also fixed a minor style issue.
=> Ingest geometry typed

metadata/metadata.go, metadata/raw.go, model/model.go
Made updates to data resource path handling to allow for absolute as well as relative paths.
=> Ingest remove copies

primitive/compute/description/preprocessing.go
Removes checks that restrict pre-featurized pipeline to run on feature vectors only.
=> Ensures selected variables are processed

go.mod, go.sum, primitive/compute/description/preprocessing.go, primitive/compute/description/primitive_steps.go
1. Adds support for date time filter in pipeline prepend creation.
2. Flags missing geobounds filter implementation that is being addressed in another issue.
=> maps datetime filter to pipeline + flags geobounds filter unimplemented

metadata/metadata.go
Add a new folder for the available datasets added by the user on the server, names _Public_.
=> Add Public folder

metadata/metadata.go, model/model.go
Added the immutable and clone fields to metadata & immutable field to variables. Makes no use of it yet.
=> Add immutable data

primitive/compute/description/cluster.go, primitive/compute/description/fully_specified.go
for uncharted-distil/distil#2095
=> added paramter for pool_features in NewRemoteSensingPretrainedStep

metadata/metadata.go
Loading types from classification output when reading metadata no longer assumes a single data resource remains in the metadata.
=> Classification Information Loading

model/model.go, primitive/compute/description/fully_specified.go, primitive/compute/description/primitive_steps.go
Added a Values field to the variable structure to hold the distinct values for categorical variables.
=> Categorical Variable Values

primitive/compute/description/cluster.go, primitive/compute/description/fully_specified.go, primitive/compute/description/primitive_steps.go
for https://github.com/uncharted-distil/distil/issues/2148
=> added pool featurisers for unpooled data clustering

primitive/compute/description/fully_specified.go, primitive/compute/description/preprocessing.go, primitive/compute/execute_pipeline_request.go
Added a fully specified filtering pipeline that can be used to filter rows in a dataset. Also added support for parquet files in fully specified pipeline executions.
=> Add prefiltering pipeline

model/model.go
Added a clone function for variables to facilitate their creation and use.
=> Dataset Cloning Name

primitive/compute/description/fully_specified.go
fixes https://github.com/uncharted-distil/distil/issues/2263
=> changed reference for construct predictions

primitive/compute/description/fully_specified.go
Added column parser to join pipeline so that non string types get handled properly.
=> Join Pipeline Parsing

primitive/compute/description/primitive_steps.go
=> Added explicit use of join type.

primitive/compute/description/cluster.go, primitive/compute/description/fully_specified.go
fixes https://github.com/uncharted-distil/distil-primitives/issues/236
=> added 'replace' param for EnrichDates, and fixed target bug

primitive/compute/description/fully_specified.go, primitive/compute/description/primitive_steps.go
Added the absolute accuracy flag as a list for the join primitive.
=> Absolute Accuracy Join

primitive/compute/description/preprocessing.go
closes uncharted-distil/distil#2951
=> The keys have to be lowered.

primitive/compute/description/cluster.go, primitive/compute/description/primitive_steps.go
Added cluster count for kmeans clustering.
=> Cluster Count

metadata/metadata.go, model/model.go, primitive/compute/description/fully_specified.go, primitive/compute/description/preprocessing.go, primitive/compute/description/preprocessing_test.go
Also changed IsTA2Field to a Variable function
=> Modified DistilRole to be an array

model/model.go, primitive/compute/description/fully_specified.go
Also added a drop column primitive to the query pipeline
=> Added label and featurize DistilRole
