uncharted-distil/distil-compute

- primitive/compute/description/builder.go
- primitive/compute/description/builder_test.go
- primitive/compute/description/preprocessing.go
- primitive/compute/description/preprocessing_test.go
- primitive/compute/description/primitive_steps.go
resolves #47 
Updates primitive steps to use dataset_map primitive along dataframe versions of column removal, semnatic type update and row filtering.  Also includes changes to ordering of wrapped primitives in pipeline to satisfy the d3m runtime.
> Migrate to dataset_map + dataframe primitives

- primitive/compute/description/preprocessing.go
- primitive/compute/description/primitive_steps.go
The column parsing primitive will convert categorical labels that are strings into integers via hashing.  MIRanking can only handle float/bool/int values, so we need to make sure the hashing is applied.
> adds categorical parsing for miranking pipeline to get hashed labels

- model/model.go
- model/schema_types.go
We had FloatType -> "float" and RealType -> "real".  THERE CAN ONLY BE ONE.
> Remove FloatType from distil types

- primitive/compute/description/preprocessing.go
- primitive/compute/description/preprocessing_test.go
If the join column type gets updated by the user, the semantic type primitive is needed in the join pipeline otherwise the join may be invalid.
> Add Semantic Type To Join Pipeline

- primitive/compute/description/preprocessing.go
- primitive/compute/ta3ta2.go
Fixes uncharted-distil/distil#1173.  Ensures that the pipeline prepend is fully skipped for timeseries.  This can be undone once the CSV reader is fixed in common primitives.
> Skip preprocessing pipeilne due to errors in required common primitives

- primitive/compute/description/primitive_steps.go
Works on ACLED but GOAT seems to fail on PHEM. No logs are available, but this should be merged into master for now.
> Goat update params

- metadata/metadata.go
- model/schema_types.go
- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing.go
- primitive/compute/description/preprocessing_test.go
- primitive/compute/description/primitive_steps.go
Added support for the unknown type. Also added the attribute semantic type to columns being used in pipelines since the new partial schema no longer has attribute type for every column.
The schema parsing code had to be updated to parse the original types and type suggestions. This enabled the propagation of the unknown type properly.
> Semantic type updates

- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing_test.go
The Sloth pipeline has been updated to have the semantic type updating since the now default unknown types cause it to fail.
> Timeseries count fix

- primitive/compute/description/preprocessing.go
The grouping field compose as written needs to have the columns be strings. The column parser must run after the grouping otherwise it may act on non string fields.
> Timeseries Prepend Primitive Order

- metadata/metadata.go
Fixes issue 116 for distil ingest. Everything defaults to unknown type if not in a schema file initially. This change makes it so that everything found in a schema file (that isn't unknown) has 1.0 probability. There is also code in there to adjust complex simon types to be probability * 1.5. Taken together, this should handle cases where the schema provides information and simon provides more depth.
> Schema Type Probability

- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing_test.go
Wrap fully specified pipelines into a structure which can be used to specify equivalent pipelines (for example MI ranking is not the complete pipeline equivalency).
> Queue pipeline requests

- model/schema_types.go
The TA2 time type appears to be more for the role field than the semantic type. Updated the type mapping to use the TA2 datetime type for distil datetime & time fields.
> Datetime Type Mapping

- primitive/compute/description/preprocessing.go
- primitive/compute/description/primitive_steps.go
Removed the output param from the sloth step creation.
Timeseries prepend no longer sets the target as parameter. That was happening because the wrong column was being used for target name. It was using the grouping column rather than the underlying target column.
> Timeseries Parameters

- model/model.go
- model/schema_types.go
This can be generalized to a bounds type at some point if required.  Its really only the client that needs to know its a geographic bounds so that it can render the underlying map data.
> Adds new geobound type

- metadata/verification.go
Ensures original type is set to classification type for imported datasets.  Caused issues with prepend not removing original types when running models, resulting in multiple semantic types being assigned.
> use classification type as original type on imports

- metadata/verification.go
- model/schema_types.go
- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing.go
- primitive/compute/description/preprocessing_test.go
Timeseries imported will not have the suggested grouping key role so additional semantic types need to be added to the pipeline to make sure the grouping compose and VAR primitives run properly.
> Timeseries Prepend & Clustering

- primitive/compute/description/cluster.go
- primitive/compute/description/primitive_steps.go
1. Picks up new column parser and applies it to pre-featurized pipelines.  Once things seems stable, we can apply it to other pipelines.
1. Fixes typing error for kmeans clusterer.
> uses optimized column parser in pipelines

- primitive/compute/description/cluster.go
- primitive/compute/description/fully_specified.go
1. The remote sensing featurizer has been updated so that it replaces the image column with feature columns, and leaves the other columns in place.  This removes the need for a horizontal concat in the pre-featurizer pipeline.
2. Updates relevant primitives in pre-featurizing pipeline to use compression
> Removes unnecessary concat after remote sensing featurizer

- primitive/compute/client.go
https://github.com/uncharted-distil/distil/issues/1342
Made the client return the API version number on successful handshake instead of nil.
> Return API version on handshake

- primitive/compute/description/cluster.go
D3M index is currently being included in the clustering step when working with pre-featurized remote sensing datasets because it is typed as an integer.  We extract only floats to and cluster on those instead.
> Cluster on float values for remote sensing

- primitive/compute/client.go
- primitive/compute/execute_pipeline_request.go
Part of fix for uncharted-distil/distil#1913.
1. Adds output support to fit request for execute pipeline calls
2. Removes explicit produce call from pipeline execute, since the fit will generate the results we use
> Fit results support

- primitive/compute/description/fully_specified.go
Fixes MI ranking failures when geocoordinates were present in a dataset.
> Ignores grouping features and metafeatures when ranking

- go.mod
- go.sum
- primitive/compute/description/cluster.go
- primitive/compute/description/fully_specified.go
Part of fix for uncharted-distil/distil#2026
Adds args for remote sensing loading and featurization primitives, allowing for GPU batching and the number of parallel jobs to be set by the TA3.  This is necessary to account for execution environment.  The TA2 has similar args it applies to remote sensing related pipelines it creates.
> Remote sensing loading and featurization args

- primitive/compute/description/preprocessing.go
- primitive/compute/description/preprocessing_test.go
- primitive/compute/description/primitive_steps.go
Part of fix for uncharted-distil/distil#2051.
Inserts a pair of vector filter primitive steps into the prepend pipeline to enforce user-specified geo coordinate filtering.  The first step filters based on x coords from the bounds array (the even elements), the second filters based on y coords (the odd elements).
> Adds geobounds filter support

- model/filter.go
Adds a convenience function to build create a bounds object from x, y, width and height.
> Create bounds from x, y, width, height

- primitive/compute/description/fully_specified.go
- primitive/compute/description/primitive_steps.go
Allows for calculations that can be shared across image query operations on a given dataset to be cached by the underlying primitive.
> Adds support for dot product cache location argument to image retrieval

- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing.go
Filtering and prefeaturized feature selection were not using the lowercase key as expected. As a result, the filter and the column selection were not acting properly in the preprocessing pipeline.
> Preprocessing Pipelines

- model/model.go
name `VarDistilRoleAugmented` to add variables that are created to enhance the UX, but are not used for creating models.
> Added a new VarDistilRole

- primitive/compute/description/fully_specified.go
Initial attempt at image featurization pipeline. It mimics the image classification pipeline until the image transfer primitive, then concatenates the output of that primitive to the input data (removing the filename column) so that the output of the pipeline has the input + the featurized image.
> Prefeaturize image pipeline

- primitive/compute/description/preprocessing.go
- primitive/compute/description/primitive_steps.go
Geobounds filtering is now reduced to a single step of the vector filter. The vector filter minimums and maximums parameters were changed to lists of lists to match the expected format.
Note that the API as used in Auto ML does not support the parsing of nested list hyper params. To test it properly, I had to modify the api utils file, which gets overwritten on api version updates. We should probably redesign the vector bounds filter primitive to be simpler and unnest the lists.
Note also that the current version of the primitive does not treat exclusive filters as being the complement (inverse) of inclusive filters. It currently considers an exclusive filter as being the rows that have every point outside of the range [min, max].
> Geobounds Fitler

- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing_test.go
part of fix for uncharted-distil/distil#2262
Removes variables that should not / can not be ranked from pipeline - previously they were left in and the downstream ta2 primitive would rank some fields that were not exposed to the user through the UI.
> remove variables that can't be ranked from mi ranking pipeline

- primitive/compute/description/fully_specified.go
Fixes case used in comparison - was failing on datasets where variables were mixed case.
> use proper case to compare

- model/model.go
- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing.go
Move the map of `ExcludedDistilRoles` to distil-compute to be used in both distil-compute and distil. Updated the couple of places where we need to filter out those distil roles.
> Fix filtering issue of Distil Roles

- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing.go
- primitive/compute/description/preprocessing_test.go
- primitive/compute/description/primitive_steps.go
- primitive/compute/ta3ta2.go
The update fuzzy join primitive supports joins using multiple features. These updates switch the join pipeline to accept lists of fields to join (along with a single accuracy value) to make use of the new ability.
> Join Multiple Columns

- model/model.go
Part of fix for uncharted-distil/distil#2546.
Uses normalized key name as header name to ensure compatibility with parquet schema character restrictions.
> use normalized name for header name

- model/filter.go
- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing.go
- primitive/compute/description/primitive_steps.go
- primitive/compute/description/step_data.go
Added support for filtering in pipelines via filter sets. Each filter set represent a set of data to be excluded from the input. The assumptions on how to compose filters follow the same assumptions as distil, whereby filters acting on the same feature are ORed together, and filters between features are ANDed together. Since these are exclusion filters, in essence the operations are reversed (!(X AND Y) = !X OR !Y). To be able to specify the same input for multiple filters, the input offset and the primitive step offset had to be split.
To OR filters, the each filter is fed the same input and their outputs are then combined together (dropping duplicates). To be able to pass in a list of inputs, some changes had to be made to the existing data reference construction. The `ListStepDataRef` …
> Filter by set

- primitive/compute/result/complex_field.peg
- primitive/compute/result/complex_field.peg.go
- primitive/compute/result/complex_field_test.go
The result parser was not handling floating of the form `1.`, which are valid in both Python and Go.
> Additional float parsing

- primitive/compute/result/complex_field.peg
- primitive/compute/result/complex_field.peg.go
- primitive/compute/result/complex_field_test.go
Part of fix for uncharted-distil/distil#2546.  Adds support for space as a separator to support ndarray values that have been serialized as part of a `to_csv` call.
> Support space as a separator

- primitive/compute/description/preprocessing.go
A previous change broke how feature indices were obtained in the preprocessing. We cannot use the column index because some features get dropped (due to not being selected in the model). However, we also cannot rely on the feature list being in the correct order. To account for this, the index mapping function now sorts the features using the column index, and then derives the select column index by counting only selected features.
> Feature Index

- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing_test.go
- primitive/compute/description/primitive_steps.go
Join accuracy is now captured as part of a specific join relationship between a field from the left dataset and the right dataset. This let's the user specify different join accuracies for every part of a join in a multi join.
> Join Pair Accuracy

- primitive/compute/description/cluster.go
- primitive/compute/description/preprocessing.go
- primitive/compute/description/preprocessing_test.go
- primitive/compute/description/primitive_steps.go
1. Moves the extract columns primitive call out of clustering since it is now more generally used
2. Adds a call to the preprocessing pipeline generation to ensure the only the features used to generate a model are selected
> Adds as step to only retain the data that was used to train the model

- model/model.go
- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing.go
- primitive/compute/description/preprocessing_test.go
There were checks in a few places to filter a variable list down to those that are valid to be processed by the TA2.  This concept got blurred with the idea of variables that should be excluded from analytic processing (ranking, outlier detection).  In one case, we have something like a grouping variable, that shouldn't be passed down to the TA2 because it is a TA3 construct, vs. a variable that is generated by the pre-featurization stage, which is perfectly valid (and rquired) for TA2 processing, but should be excluded from analysis tasks.  The `IsTA2Field` check has been updated to properly handle all necessary roles, and replaces calls to analysis processing set in a few places.
> Variable validity check

- model/schema_types.go
- primitive/compute/description/fully_specified.go
- primitive/compute/description/preprocessing_test.go
Updated join to handle geobounds being used in the join. They join on the underlying coordinates column, but need to be tagged as a bounding polygon to trigger the proper join approach.
> Tag bounding polygon

- primitive/compute/description/preprocessing.go
Switched how the initial prepend feature selection works to take the first n columns, where n is the highest column index in the list of features.
> Prediction Outliers
